# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uuQNloYjJR_sMjeZiYIK8KEGB6xS9mdc
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

conn = sqlite3.connect('sales_data.db')
cursor = conn.cursor()

# Create table
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY,
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")
# Insert sample data
cursor.executescript("""
INSERT INTO sales (product, quantity, price) VALUES
('Laptop', 1, 1200.00),
('Mouse', 5, 25.00),
('Keyboard', 3, 75.00),
('Laptop', 2, 1150.50),
('Monitor', 2, 300.00),
('Mouse', 10, 22.75),
('Headphones', 8, 45.00),
('Webcam', 4, 80.00),
('External Hard Drive', 2, 120.00),
('Laptop', 1, 1300.00),
('Keyboard', 2, 80.00),
('Headphones', 5, 40.00),
('Webcam', 3, 75.00),
('External Hard Drive', 1, 110.00),
('Monitor', 1, 320.00),
('CPU', 1, 500.00),
('CPU', 2, 550.00);
""")

conn.commit()

query = """
SELECT product, SUM(quantity) AS total_quantity, SUM(quantity * price) AS total_revenue
FROM sales
GROUP BY product;
"""

df = pd.read_sql_query(query, conn)
conn.close()
print("Sales Summary:\n")
print(df)

#  bar chart
plt.figure(figsize=(10, 6))
plt.bar(df['product'], df['total_revenue'], color='skyblue')
plt.xlabel('Product')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Product')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig("sales_chart.png")
plt.show()

from google.colab import files

files.download('sales_chart.png')
files.download('sales_data.db')

